### ISSUE TITLE
Opening settings menu causes minecraft to crash

### ISSUE THREAD

**Issue by horseloyal** [Ryhon0/SimpleAutoswitch#2] opened 2024-06-05 17:01 UTC
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-06-05 18:00:35
Description: Unexpected error

java.lang.IncompatibleClassChangeError: class xyz.ryhon.simpleautoswitch.AutoswitchSettingsScreen$SwitchButton overrides final method net.minecraft.class_339.method_25394(Lnet/minecraft/class_332;IIF)V
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at xyz.ryhon.simpleautoswitch.SimpleAutoswitch.lambda$onInitialize$0(SimpleAutoswitch.java:65)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$zlp000$fabric-lifecycle-events-v1$onStartTick(class_310.java:5742)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1281)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Ryhon0** [comment] 2024-06-05 17:08
Duplicate of #1

**Closed as completed by Ryhon0** 2024-06-05 17:08 UTC
